### ISSUE TITLE
How can I store the SMTP password safely?

### ISSUE THREAD

**Issue by spinningarrow** [deployd/dpd-email#16]
Ideally, I'd like to get it from an environment variable. Is it possible to do this?

**Comment by andreialecu** [comment]
Doesn't seem to be implemented by default, but feel free to fork. The code is very simple:

https://github.com/deployd/dpd-email/blob/master/index.js

**Comment by spinningarrow** [comment]
I opened a PR: #17. Do take a look at it when you get the time, thanks!

**Comment by spinningarrow** [comment]
I think this has been fixed and the latest release (0.1.1) has this change. Should we close this issue?

**Comment by ericfong** [comment]
Merged and published to npm
