### ISSUE TITLE
not working with server.

### ISSUE THREAD

**Issue by hendry91** [deployd/dpd-email#20]
Hi, I use your project with `npm install`, then I use `node server.js` to start the deployd, I'm able to go in the dashboard, but I only get  the collection and users collection, don't have "email" to do setting.

Do you know how to solve it? Thanks.

My server.js file:
> server.js

```
var deployd = require('deployd');

var server = deployd({
  port: process.env.PORT || 9090,
  env: 'staging',
  db: {
    host: 'my.mongolab.com',
    port: mypost,
    name: 'myname',
    credentials: {
      username: 'myusername',
      password: 'mypass'
    }
  }
});

server.listen();

server.on('listening', function() {
  console.log("Server is listening");
});

server.on('error', function(err) {
  console.error(err);
  process.nextTick(function() { // Give the server a chance to return an error
    process.exit();
  });
});
```

**Comment by rgolea** [comment]
do you have deployd and dpd-email installed and saved in your local project?

do: npm install --save deployd dpd-email

**Comment by hendry91** [comment]
yes, I did. I think is my server.js problem.

I try to redo the step, my step is:
1. download this git project.
2. open cmd - > cd to dpd-email-master
3. npm install --save deployd dpd-email
4. npm install
5. node server.js
6. open http://localhost:9090/dashboard
7. my RESOURCES button there only got Collection and Users collection. don't have "email".

If I use dpd create test-email -> npm install --save deployd dpd-email -> dpd to start deployd.
then open http://localhost:2403/dashboard, it work, I get the "email".

But I can't use dpd to start the deployd, I must use `forever start server.js` on my host server instead of `dpd`.

**Comment by rgolea** [comment]
what? no...

make a new folder project. npm init, then npm install --save deployd dpd-email. paste your script and done.

**Comment by hendry91** [comment]
I just noticed that, can directly use `dpd create ` instead of using package.json to install/create.
I'm newbie, still learning. now it works.
Thanks you. :D

**Comment by rgolea** [comment]
I've made a tutorial. will do more

http://www.youtube.com/playlist?list=PLrceyQl0Cmplzid4tveBvYBzHOSot6vjk
