### ISSUE TITLE
Where is dashboard?

### ISSUE THREAD

**Issue by ezra-obiwale** [deployd/dpd-email#22]
Pursuant to issue #6, as of the current version of deployd (0.8.9), the dashboard is nowhere to be found as there's no *Email* link in the *Resources* dropdown.

I have removed and reinstalled the module, restarted both deployd and the system several times, all to no avail.

I am on windows 10.

**Comment by ericfong** [comment]
Sorry, personally I have no time to maintain this project. I know that is bad. Do you have time to take a look on it? 
The actually code is really simple. 

thx

**Comment by ezra-obiwale** [comment]
It's alright. I get how it is.

So yeah, I don't mind taking a swing at it.

Cheers.

**Comment by ezra-obiwale** [comment]
Hi,

I really do not understand what just happened only that I installed the dpd-fileupload module and the **Email** link appeared with it.

I'll still look into it though.
