### ISSUE TITLE
line 21 && to ||?

### ISSUE THREAD

**Issue by yujusystems** [deployd/dpd-email#23]
I was having an issue making it work and found this code below at the ine 21.

if (this.config.username != '' && typeof process.env.DPD_EMAIL_USERNAME != 'undefined') {

I was wondering you meant || instead of &&.

**Comment by rgolea** [comment]
@yujusystems no, see the line above... https://github.com/deployd/dpd-email/blob/master/index.js#L20

**Comment by andreialecu** [comment]
@rgolea - Actually he is right. 

@yujusystems send a PR for this and we'll accept it.
