### ISSUE TITLE
Can't Send HTML Email With Mailgun

### ISSUE THREAD

**Issue by tomagig** [deployd/dpd-email#8]
```
dpd.email.post({
  to: 'me@mysite.com',
  from: 'Webmaster <webmaster@qso.directory>',
  subject: "Hello!",
  html: "<h1>Hey,</h1><p>Thank you for registering for MyApp!</p>"
}, function() {});
```

I get the error "[Error: Can't set headers after they are sent.]" if I use the code above, however if I change html to text it sends but I see the html tags.

**Comment by NicolasRitouet** [comment]
I close this issue since the new version of dpd-email changes completely the way we send html emails.
